name: Tag and publish release
description: Create a new Git tag and publish a release on GitHub whenever the npm package version has changed.
inputs:
  checkout_token:
    description: GitHub token
    default: ${{ github.token }}
    required: false
  checkout_repository:
    description: The repository to checkout
    default: ${{ github.repository }}
    required: false
  checkout_depth:
    description: The depth of the git history to fetch
    default: "1"
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.checkout_depth }}
        repository: ${{ inputs.checkout_repository }}

    - name: Create tag on NPM package version change
      uses: abdul-alhasany/actions/create-tag@main
      id: tag

    - name: Setup pnpm and install dependencies
      if: steps.tag.outputs.tag-created == 'true'
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Publish release on GitHub
      run: pnpx changelogithub
      if: steps.tag.outputs.tag-created == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.checkout_token }}

    - name: Show log message
      shell: bash
      run: echo "Release published successfully"
      if: steps.tag.outputs.tag-created == 'true'

    - name: Show log message
      if: steps.tag.outputs.tag-created == 'false'
      shell: bash
      # fail the workflow if the tag already exists
      run: |
        echo "::warning::No release published as the tag ${{ steps.tag.outputs.tag }} already exists"
        exit 1
