name: Tag and publish release

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  tag-npm-release:
    name: Tag and publish github release
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v4

       - name: Create Release From Tag
         uses: ./create-gh-release